import type { Metadata } from "next"
import Link from "next/link"
import { Building2, Clock, Mail, MapPin, MessageCircle, Phone } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { business } from "@/lib/business-info"

export const metadata: Metadata = { title: "Contact Packaging Company in Hyderabad", description: "Contact MS Paper Products in Balkampet, Hyderabad for custom packaging, commercial printing, bulk orders, quotations, call backs, and factory visits.", alternates: { canonical: "/contact" } }

export default function ContactPage() {
  const cards = [
    { icon: Phone, title: "Call Sales", text: business.phoneDisplay, href: business.phoneHref },
    { icon: MessageCircle, title: "WhatsApp", text: "Discuss your requirement", href: business.whatsappUrl },
    { icon: Mail, title: "Email", text: business.email, href: `mailto:${business.email}` },
    { icon: MapPin, title: "Factory Location", text: "Balkampet, Hyderabad", href: business.mapUrl },
  ]
  return <main>
    <section className="bg-primary py-16 text-primary-foreground md:py-24"><div className="mx-auto max-w-7xl px-4"><p className="font-semibold uppercase tracking-widest text-accent">Business enquiries</p><h1 className="mt-3 text-balance text-4xl font-bold md:text-6xl">Let&apos;s plan your packaging or print requirement</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-primary-foreground/70">Share your product, dimensions, quantity, material, printing, finish, and delivery location for a more useful response from our Hyderabad team.</p></div></section>
    <section className="py-12"><div className="mx-auto max-w-7xl px-4"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map((card) => <a key={card.title} href={card.href} target={card.href.startsWith("http") ? "_blank" : undefined} rel={card.href.startsWith("http") ? "noopener noreferrer" : undefined} className="rounded-xl border border-border bg-card p-5 transition hover:border-accent"><card.icon className="size-7 text-accent" /><h2 className="mt-4 font-bold text-primary">{card.title}</h2><p className="mt-1 text-sm text-muted-foreground">{card.text}</p></a>)}</div></div></section>
    <section className="pb-16"><div className="mx-auto grid max-w-7xl gap-10 px-4 lg:grid-cols-[1.05fr_.95fr]"><div><h2 className="text-3xl font-bold text-primary">Quick Enquiry</h2><p className="mt-3 text-muted-foreground">For bulk orders, call backs, custom manufacturing, and quotation requests.</p><form action={`mailto:${business.email}`} method="post" encType="text/plain" className="mt-7 grid gap-5 sm:grid-cols-2"><div className="flex flex-col gap-2"><Label htmlFor="name">Full name</Label><Input id="name" name="Name" required autoComplete="name" /></div><div className="flex flex-col gap-2"><Label htmlFor="company">Company</Label><Input id="company" name="Company" autoComplete="organization" /></div><div className="flex flex-col gap-2"><Label htmlFor="phone">Phone</Label><Input id="phone" name="Phone" type="tel" required autoComplete="tel" /></div><div className="flex flex-col gap-2"><Label htmlFor="email">Email</Label><Input id="email" name="Email" type="email" required autoComplete="email" /></div><div className="flex flex-col gap-2 sm:col-span-2"><Label htmlFor="requirement">Requirement</Label><Textarea id="requirement" name="Requirement" required rows={6} placeholder="Product, dimensions, quantity, material, print, finish, and delivery location" /></div><Button type="submit" className="bg-accent text-accent-foreground sm:col-span-2">Send Enquiry by Email</Button></form></div><aside className="flex flex-col gap-6"><Card><CardContent className="p-6"><Building2 className="size-8 text-accent" /><h2 className="mt-4 text-2xl font-bold text-primary">Visit MS Paper Products</h2><p className="mt-3 leading-relaxed text-muted-foreground">{business.address}</p><p className="mt-4 flex gap-2 text-sm"><Clock className="size-5 text-accent" />{business.hoursLabel}</p><Button asChild variant="outline" className="mt-5 border-accent text-primary"><a href={business.mapUrl} target="_blank" rel="noopener noreferrer">Open in Google Maps</a></Button></CardContent></Card><Card><CardContent className="p-6"><h2 className="text-xl font-bold text-primary">Factory Visit & Call Back</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Contact our team before visiting so we can schedule the right production or sales representative for your requirement.</p><div className="mt-5 flex flex-wrap gap-3"><Button asChild className="bg-accent text-accent-foreground"><a href={business.phoneHref}>Request Call Back</a></Button><Button asChild variant="outline"><a href={`mailto:${business.email}?subject=Factory Visit Request`}>Plan Factory Visit</a></Button></div></CardContent></Card></aside></div></section>
    <section className="bg-muted py-12"><div className="mx-auto max-w-7xl px-4"><h2 className="text-2xl font-bold text-primary">Serving Hyderabad and beyond</h2><p className="mt-3 max-w-4xl leading-relaxed text-muted-foreground">We support business requirements across {business.serviceAreas.join(", ")}.</p><div className="mt-5 flex gap-5 text-sm font-semibold"><Link href="/products" className="text-accent hover:underline">Explore products</Link><Link href="/services" className="text-accent hover:underline">Printing services</Link><Link href="/resources" className="text-accent hover:underline">Planning guides</Link></div></div></section>
  </main>
}
