import Link from "next/link"
import { ArrowRight, CheckCircle2, Factory, PackageCheck, Printer, Truck } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb"
import type { IndustrySolution } from "@/lib/industry-solutions"
import { business } from "@/lib/business-info"

const process = [
  { name: "Requirement", icon: PackageCheck },
  { name: "Design & Prepress", icon: Printer },
  { name: "Manufacturing", icon: Factory },
  { name: "Inspection & Dispatch", icon: Truck },
]

export default function IndustrySolutionPage({ solution }: { solution: IndustrySolution }) {
  const canonical = `https://mspaperproducts.com/solutions/${solution.slug}`
  const schemas = [
    { "@context": "https://schema.org", "@type": "Service", name: solution.title, description: solution.description, provider: { "@id": "https://mspaperproducts.com/#organization" }, areaServed: business.serviceAreas, url: canonical },
    { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: solution.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) },
    { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: "https://mspaperproducts.com" }, { "@type": "ListItem", position: 2, name: "Solutions", item: "https://mspaperproducts.com/packaging-solutions" }, { "@type": "ListItem", position: 3, name: solution.title, item: canonical }] },
  ]

  return <main>
    {schemas.map((schema, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />)}
    <div className="mx-auto max-w-7xl px-4 py-4"><Breadcrumb><BreadcrumbList><BreadcrumbItem><BreadcrumbLink asChild><Link href="/">Home</Link></BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator /><BreadcrumbItem><BreadcrumbLink asChild><Link href="/packaging-solutions">Solutions</Link></BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator /><BreadcrumbItem><BreadcrumbPage>{solution.title}</BreadcrumbPage></BreadcrumbItem></BreadcrumbList></Breadcrumb></div>
    <section className="bg-primary py-16 text-primary-foreground md:py-24"><div className="mx-auto max-w-7xl px-4"><p className="font-semibold uppercase tracking-widest text-accent">Factory-direct B2B solutions</p><h1 className="mt-3 max-w-4xl text-balance text-4xl font-bold md:text-6xl">{solution.title} in Hyderabad</h1><p className="mt-5 max-w-3xl text-lg leading-relaxed text-primary-foreground/75">{solution.description}</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="bg-accent text-accent-foreground"><Link href="/contact">Request a Quote <ArrowRight className="size-4" /></Link></Button><Button asChild variant="outline" className="border-primary-foreground/40 bg-transparent text-primary-foreground hover:bg-primary-foreground hover:text-primary"><a href={business.whatsappUrl} target="_blank" rel="noopener noreferrer">Discuss on WhatsApp</a></Button></div></div></section>
    <section className="py-14"><div className="mx-auto grid max-w-7xl gap-10 px-4 lg:grid-cols-[1.15fr_.85fr]"><div><h2 className="text-3xl font-bold text-primary">Made for Business Requirements</h2><p className="mt-4 leading-relaxed text-muted-foreground">{solution.overview}</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{solution.applications.map((item) => <div key={item} className="flex gap-3 rounded-lg border border-border p-4"><CheckCircle2 className="size-5 shrink-0 text-accent" /><span className="text-sm font-medium">{item}</span></div>)}</div></div><aside className="rounded-xl bg-muted p-6"><h2 className="text-xl font-bold text-primary">Recommended Products</h2><ul className="mt-4 flex flex-col gap-3">{solution.products.map((item) => <li key={item} className="flex items-center justify-between rounded-md bg-card px-4 py-3 text-sm font-semibold shadow-xs"><span>{item}</span><ArrowRight className="size-4 text-accent" /></li>)}</ul><Link href="/products" className="mt-5 inline-flex font-semibold text-accent hover:underline">Browse all products</Link></aside></div></section>
    <section className="bg-muted py-14"><div className="mx-auto max-w-7xl px-4"><h2 className="text-center text-3xl font-bold text-primary">From Requirement to Dispatch</h2><div className="mt-8 grid gap-4 md:grid-cols-4">{process.map((step, index) => <div key={step.name} className="rounded-lg border border-border bg-card p-5 text-center"><step.icon className="mx-auto size-8 text-accent" /><p className="mt-3 text-xs font-bold text-accent">STEP {index + 1}</p><h3 className="mt-1 font-bold text-primary">{step.name}</h3></div>)}</div></div></section>
    <section className="py-14"><div className="mx-auto grid max-w-7xl gap-8 px-4 lg:grid-cols-2"><div><h2 className="text-3xl font-bold text-primary">Why MS Paper Products</h2><ul className="mt-5 flex flex-col gap-3 text-muted-foreground">{["Factory-direct coordination", "Custom materials, sizes, printing, and finishes", "Bulk business orders welcome", "Quality inspection before dispatch", "Hyderabad support with PAN India service"].map((item) => <li key={item} className="flex gap-3"><CheckCircle2 className="size-5 shrink-0 text-accent" />{item}</li>)}</ul><div className="mt-7 flex flex-wrap gap-4 text-sm font-semibold"><Link href="/printing" className="text-accent hover:underline">Printing services</Link><Link href="/products" className="text-accent hover:underline">Product catalog</Link><Link href="/resources" className="text-accent hover:underline">Packaging resources</Link><Link href="/about" className="text-accent hover:underline">About our company</Link><Link href="/contact" className="text-accent hover:underline">Contact sales</Link></div></div><div><h2 className="text-3xl font-bold text-primary">Frequently Asked Questions</h2><Accordion type="single" collapsible className="mt-4">{solution.faqs.map((faq, index) => <AccordionItem key={faq.question} value={`faq-${index}`}><AccordionTrigger>{faq.question}</AccordionTrigger><AccordionContent>{faq.answer}</AccordionContent></AccordionItem>)}</Accordion></div></div></section>
    <section className="bg-primary py-12 text-primary-foreground"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-5 px-4 md:flex-row md:items-center"><div><h2 className="text-3xl font-bold">Planning a bulk requirement?</h2><p className="mt-2 text-primary-foreground/70">Share your product, quantity, dimensions, material, and delivery location.</p></div><Button asChild className="bg-accent text-accent-foreground"><Link href="/contact">Start Your Enquiry</Link></Button></div></section>
  </main>
}
