export interface Product {
  id: string
  title: string
  category: string
  description: string
  useCase: string
  image: string
  slug: string
  specifications: {
    material?: string
    sizes?: string[]
    gsm?: string
    moq?: string
    printing?: string[]
    finishing?: string[]
  }
  features?: string[]
  gallery?: string[]
}

export const categories = [
  { id: "all", name: "All Products", icon: "grid" },
  { id: "pharma", name: "Pharma & Medical Packaging", icon: "cross" },
  { id: "luxury", name: "Luxury Paper Bags", icon: "sparkles" },
  { id: "kraft", name: "Kraft & Retail Bags", icon: "shopping-bag" },
  { id: "wedding", name: "Wedding & Gifting Bags", icon: "gift" },
  { id: "food-grade", name: "Food Grade Bags", icon: "utensils" },
  { id: "boxes", name: "Sweet & Designer Boxes", icon: "package" },
  { id: "corporate", name: "Corporate & Event Bags", icon: "briefcase" },
  { id: "stationery", name: "Stationery & Printing", icon: "file-text" },
]

export const products: Product[] = [
  // Pharma & Medical Packaging
  {
    id: "pharma-001",
    title: "Medicine Boxes",
    category: "pharma",
    description:
      "High-quality pharma-grade medicine boxes for tablets, capsules, syrups, and nutraceutical packaging. Hygienic, durable, and fully customizable.",
    useCase: "Pharmaceutical companies, medical distributors, nutraceutical brands, hospitals & clinics",
    image: "/medicine-boxes.jpg",
    slug: "medicine-boxes",
    specifications: {
      material: "Pharma-grade paperboard",
      sizes: ["Custom sizes available"],
      gsm: "250-350 GSM",
      moq: "1000 pieces",
      printing: ["Offset Printing", "QR Code", "Barcode", "Batch Printing"],
      finishing: ["Spot UV", "Foiling", "Matte/Gloss Lamination"],
    },
    features: [
      "Pharma-safe material",
      "Tamper-evident closure",
      "Custom sizes & structures",
      "High-precision print quality",
      "QR, barcode & batch printing",
      "Spot UV, Foiling, Matte/Gloss lamination",
      "Damage-resistant during transport",
    ],
    gallery: [
      "/medicine-boxes.jpg",
      "/medicine-box-variant-1.jpg",
      "/medicine-box-variant-2.jpg",
      "/medicine-box-variant-3.jpg",
    ],
  },
  {
    id: "pharma-002",
    title: "Tablet Strip Boxes",
    category: "pharma",
    description:
      "Tablet strip boxes designed for capsules and tablets, with precise print space for dosage, batch details, and compliance labeling.",
    useCase: "Tablet manufacturers, pharmaceutical packaging, blister pack protection",
    image: "/tablet-strip-boxes.jpg",
    slug: "tablet-strip-boxes",
    specifications: {
      material: "Medical-grade carton board",
      sizes: ["Single strip", "Multi-strip", "Custom sizes"],
      gsm: "250-300 GSM",
      moq: "1000 pieces",
      printing: ["Offset Printing", "Dosage marking", "Batch printing"],
      finishing: ["Matte lamination", "Spot UV", "Fold-lock structure"],
    },
    features: [
      "Strong protection during transport",
      "Maintains shape integrity",
      "Clear printing for compliance",
      "Single-strip & multi-strip options",
      "Fold-lock structure",
      "Barcode & batch details support",
    ],
    gallery: ["/tablet-strip-boxes.jpg"],
  },
  {
    id: "pharma-003",
    title: "Syrup Bottle Cartons",
    category: "pharma",
    description: "Custom-fit syrup bottle boxes that ensure safe transport and clear pharmaceutical branding.",
    useCase: "Syrup manufacturers, cough syrup packaging, liquid medicine boxes",
    image: "/syrup-bottle-cartons.jpg",
    slug: "syrup-bottle-cartons",
    specifications: {
      material: "Pharma-grade carton board",
      sizes: ["30ml", "60ml", "100ml", "150ml bottle fit"],
      gsm: "300-350 GSM",
      moq: "1000 pieces",
      printing: ["Offset printing", "QR codes", "Holographic seal areas"],
      finishing: ["Matte/Gloss lamination", "Inserts available"],
    },
    features: [
      "Secure bottle holding",
      "Tear-resistant structure",
      "Clear pharmaceutical branding",
      "QR code & holographic seal support",
      "Inserts for bottle stability",
      "Custom bottle size fit",
    ],
    gallery: ["/syrup-bottle-cartons.jpg"],
  },
  {
    id: "pharma-004",
    title: "Medical Kit Boxes",
    category: "pharma",
    description:
      "Packaging for diagnostic kits, rapid test kits, and hospital-use medical kits with premium structural strength.",
    useCase: "Diagnostic test kits, first-aid kits, at-home medical testing, hospital supplies",
    image: "/medical-kit-boxes.jpg",
    slug: "medical-kit-boxes",
    specifications: {
      material: "Medical-grade rigid board",
      sizes: ["Custom sizes for kit contents"],
      gsm: "350-400 GSM",
      moq: "500 pieces",
      printing: ["High-precision medical printing", "Instruction manuals"],
      finishing: ["Internal partitions", "Security seals", "Sterile presentation"],
    },
    features: [
      "Designed for accuracy & strength",
      "Sterile presentation",
      "Internal partitions available",
      "Security seal support",
      "Space for instruction manuals",
      "Multi-product arrangements",
    ],
    gallery: ["/medical-kit-boxes.jpg"],
  },
  {
    id: "pharma-005",
    title: "Blister Pack Boxes",
    category: "pharma",
    description:
      "Durable pharma folding cartons for blister packs with tamper-evident locking and sharp print clarity.",
    useCase: "Blister pack packaging, tablet protection, capsule strip boxes",
    image: "/blister-pack-boxes.jpg",
    slug: "blister-pack-boxes",
    specifications: {
      material: "Pharma folding carton board",
      sizes: ["Multiple strip quantities", "Custom sizes"],
      gsm: "250-300 GSM",
      moq: "1000 pieces",
      printing: ["Medical-compliant printing", "Dosage & batch details"],
      finishing: ["Tamper-evident lock", "Moisture-resistant coating"],
    },
    features: [
      "Excellent bending protection",
      "Moisture exposure protection",
      "Tamper-evident locking",
      "Medical-compliant print space",
      "Multiple strip support",
      "Sharp print clarity",
    ],
    gallery: ["/blister-pack-boxes.jpg"],
  },
  {
    id: "pharma-006",
    title: "Ointment / Tube Boxes",
    category: "pharma",
    description: "Premium folding cartons for ointment tubes, gel tubes, cosmetic medicated tubes, and topical creams.",
    useCase: "Ointment packaging, gel tubes, pain relief creams, medicated skincare",
    image: "/ointment-tube-boxes.jpg",
    slug: "ointment-tube-boxes",
    specifications: {
      material: "Medical-safe carton board",
      sizes: ["Custom tube sizes", "5g to 100g capacity"],
      gsm: "300 GSM",
      moq: "1000 pieces",
      printing: ["High clarity instruction printing", "Regulatory details"],
      finishing: ["Matte finish", "Secure tube holding structure"],
    },
    features: [
      "Secure tube holding without squeezing",
      "Suitable for medicated skincare",
      "High clarity regulatory printing",
      "Gel & cream tube compatible",
      "Pain relief cream packaging",
      "Cosmetic medical formulations",
    ],
    gallery: ["/ointment-tube-boxes.jpg"],
  },
  {
    id: "pharma-007",
    title: "Supplement / Nutraceutical Boxes",
    category: "pharma",
    description:
      "Brand-centric packaging for supplements, vitamins, herbal capsules, protein sachets, and nutraceutical products.",
    useCase: "Supplement brands, vitamins, herbal capsules, protein packaging, nutraceutical products",
    image: "/supplement-boxes.jpg",
    slug: "supplement-nutraceutical-boxes",
    specifications: {
      material: "Premium carton board",
      sizes: ["Bottle packaging", "Sachet boxes", "Strip packaging"],
      gsm: "300-350 GSM",
      moq: "500 pieces",
      printing: ["Premium branding", "FDA-friendly printing"],
      finishing: ["Gloss/Matte lamination", "Foiling", "Embossing"],
    },
    features: [
      "Premium branding support",
      "Strong structure",
      "FDA-friendly printing clarity",
      "Elevates supplement brands",
      "Attractive visuals",
      "Durable carton board",
    ],
    gallery: ["/supplement-boxes.jpg"],
  },
  {
    id: "pharma-008",
    title: "Diagnostic Kit Sleeve Boxes",
    category: "pharma",
    description:
      "Sleeve-style packaging for diagnostic kits, strips, and medical papers with clean slide-in structure.",
    useCase: "Pregnancy kits, diabetic strips, medical test strips, diagnostic devices",
    image: "/diagnostic-kit-sleeves.jpg",
    slug: "diagnostic-kit-sleeve-boxes",
    specifications: {
      material: "Medical-grade sleeve carton",
      sizes: ["Pregnancy kit size", "Test strip sizes", "Custom sizes"],
      gsm: "300 GSM",
      moq: "1000 pieces",
      printing: ["Precise labeling areas", "Medical compliance printing"],
      finishing: ["Easy slide-in structure", "High-strength board"],
    },
    features: [
      "Easy slide-in access",
      "High-strength board",
      "Precise labeling areas",
      "Pregnancy kit compatible",
      "Diabetic strip packaging",
      "Minimalist medical design",
    ],
    gallery: ["/diagnostic-kit-sleeves.jpg"],
  },
  {
    id: "pharma-009",
    title: "Pharma Shipping & Transport Boxes",
    category: "pharma",
    description:
      "Strong corrugated shipping boxes for pharma logistics, designed to protect inner cartons during transport.",
    useCase: "Bulk pharma shipping, tablets, syrups, kits, medical instruments logistics",
    image: "/pharma-shipping-boxes.jpg",
    slug: "pharma-shipping-transport-boxes",
    specifications: {
      material: "High-strength corrugated board",
      sizes: ["Custom bulk shipping sizes"],
      gsm: "5-ply / 7-ply corrugated",
      moq: "500 pieces",
      printing: ["Handling instructions", "Medical labeling"],
      finishing: ["Moisture-resistant coating", "Stacking stability"],
    },
    features: [
      "High-strength corrugated material",
      "Clear medical labeling",
      "Stacking stability",
      "Moisture-resistant coating options",
      "Bulk shipping protection",
      "Handling instruction printing",
    ],
    gallery: ["/pharma-shipping-boxes.jpg"],
  },

  // Luxury Paper Bags
  {
    id: "lux-001",
    title: "Premium Luxury Shopping Bag",
    category: "luxury",
    description: "High-end shopping bags with custom branding, perfect for jewelry, cosmetics, and luxury retail.",
    useCase: "Luxury retail, jewelry stores, boutiques",
    image: "/luxury-printed-paper-bag-premium.jpg",
    slug: "premium-luxury-shopping-bag",
    specifications: {
      material: "Art Card / Ivory Board",
      sizes: ["8x10x4", "10x12x5", "12x15x6"],
      gsm: "250-350 GSM",
      moq: "500 pieces",
      printing: ["Offset Printing", "Custom Branding"],
      finishing: ["Gold Foiling", "Spot UV", "Matte Lamination"],
    },
    features: ["Rope handles", "Reinforced base", "Premium finish"],
    gallery: [
      "/luxury-printed-paper-bag-premium.jpg",
      "/luxury-gold-paper-bag-closeup.jpg",
      "/luxury-paper-bag-with-logo.jpg",
      "/premium-shopping-bags-display.jpg",
    ],
  },
  {
    id: "lux-002",
    title: "Designer Jewelry Bag",
    category: "luxury",
    description: "Elegant small-sized bags specifically designed for jewelry packaging with soft finish.",
    useCase: "Jewelry packaging, premium gifting",
    image: "/elegant-white-jewelry-paper-bag-with-silver-foil-l.jpg",
    slug: "designer-jewelry-bag",
    specifications: {
      material: "Art Card",
      sizes: ["4x6x2", "6x8x3"],
      gsm: "300 GSM",
      moq: "1000 pieces",
      printing: ["Flexo Printing", "Digital Printing"],
      finishing: ["Silver Foiling", "Embossing"],
    },
    features: ["Soft touch lamination", "Satin ribbon handles", "Interior lining"],
    gallery: ["/elegant-white-jewelry-paper-bag-with-silver-foil-l.jpg"],
  },
  {
    id: "lux-003",
    title: "Cosmetic Retail Bag",
    category: "luxury",
    description: "Vibrant printed bags for cosmetics and beauty products with glossy finish.",
    useCase: "Cosmetic stores, beauty salons",
    image: "/vibrant-cosmetic-paper-bag-with-glossy-finish-and-.jpg",
    slug: "cosmetic-retail-bag",
    specifications: {
      material: "Coated Paper",
      sizes: ["8x10x4", "10x13x5"],
      gsm: "250 GSM",
      moq: "500 pieces",
      printing: ["Full Color Offset"],
      finishing: ["Gloss Lamination", "Spot UV"],
    },
    features: ["Die-cut handles", "Full color printing", "Brand customization"],
    gallery: ["/vibrant-cosmetic-paper-bag-with-glossy-finish-and-.jpg"],
  },

  // Kraft & Retail Bags
  {
    id: "kraft-001",
    title: "Brown Kraft Shopping Bag",
    category: "kraft",
    description: "Eco-friendly natural brown kraft bags perfect for organic and sustainable brands.",
    useCase: "Organic stores, eco-friendly retail, cafes",
    image: "/brown-kraft-shopping-bag.jpg",
    slug: "brown-kraft-shopping-bag",
    specifications: {
      material: "Natural Kraft Paper",
      sizes: ["8x10x4", "10x12x5", "12x16x6"],
      gsm: "120-150 GSM",
      moq: "500 pieces",
      printing: ["Flexo Printing", "Screen Printing"],
      finishing: ["Natural finish", "Optional branding"],
    },
    features: ["100% recyclable", "Twisted paper handles", "Biodegradable"],
    gallery: ["/brown-kraft-shopping-bag.jpg"],
  },
  {
    id: "kraft-002",
    title: "White Kraft Paper Bag",
    category: "kraft",
    description: "Clean white kraft bags ideal for bakeries, restaurants, and food retail.",
    useCase: "Bakeries, food delivery, retail stores",
    image: "/white-kraft-paper-bag.jpg",
    slug: "white-kraft-paper-bag",
    specifications: {
      material: "White Kraft Paper",
      sizes: ["6x9x3", "8x10x4", "10x13x5"],
      gsm: "100-120 GSM",
      moq: "1000 pieces",
      printing: ["Flexo Printing"],
      finishing: ["Food-safe coating optional"],
    },
    features: ["Food-safe", "Grease resistant option", "Flat or twisted handles"],
    gallery: ["/white-kraft-paper-bag.jpg"],
  },
  {
    id: "kraft-003",
    title: "Die-Cut Handle Kraft Bag",
    category: "kraft",
    description: "Modern kraft bags with die-cut handles for easy carrying and stylish appeal.",
    useCase: "Retail shops, boutiques, gift stores",
    image: "/die-cut-kraft-bag.jpg",
    slug: "die-cut-handle-kraft-bag",
    specifications: {
      material: "Kraft Paper",
      sizes: ["10x12x4", "12x15x5"],
      gsm: "150 GSM",
      moq: "500 pieces",
      printing: ["Custom logo printing"],
      finishing: ["Reinforced die-cut handles"],
    },
    features: ["Comfortable grip", "Strong reinforcement", "Eco-friendly"],
    gallery: ["/die-cut-kraft-bag.jpg"],
  },
  {
    id: "kraft-004",
    title: "Retail Shopping Bag",
    category: "kraft",
    description: "Versatile retail bags suitable for various products and everyday shopping.",
    useCase: "General retail, shopping malls, stores",
    image: "/retail-shopping-bag.jpg",
    slug: "retail-shopping-bag",
    specifications: {
      material: "Kraft/White Paper",
      sizes: ["All sizes available"],
      gsm: "100-200 GSM",
      moq: "500 pieces",
    },
    features: ["Customizable", "Durable", "Cost-effective"],
    gallery: ["/retail-shopping-bag.jpg"],
  },

  // Wedding & Gifting Bags
  {
    id: "wedding-001",
    title: "Wedding Return Gift Bag",
    category: "wedding",
    description: "Elegant return gift bags for wedding favors with premium finish and customization.",
    useCase: "Wedding favors, return gifts",
    image: "/wedding-return-gift-bag.jpg",
    slug: "wedding-return-gift-bag",
    specifications: {
      material: "Art Card / Ivory Board",
      sizes: ["6x8x3", "8x10x4"],
      gsm: "250-300 GSM",
      moq: "500 pieces",
      printing: ["Custom design printing"],
      finishing: ["Gold/Silver foiling", "Ribbon handles", "Embossing"],
    },
    features: ["Customizable design", "Premium ribbon", "Personalization available"],
    gallery: ["/wedding-return-gift-bag.jpg"],
  },
  {
    id: "wedding-002",
    title: "Embossed Luxury Wedding Bag",
    category: "wedding",
    description: "Premium wedding bags with embossed patterns and metallic finishes.",
    useCase: "High-end weddings, corporate gifting",
    image: "/embossed-luxury-wedding-bag.jpg",
    slug: "embossed-luxury-wedding-bag",
    specifications: {
      material: "Textured Art Card",
      sizes: ["8x10x4", "10x12x5"],
      gsm: "300-350 GSM",
      moq: "300 pieces",
      finishing: ["Embossing", "Foiling", "UV coating"],
    },
    features: ["Embossed patterns", "Luxury appeal", "Satin handles"],
    gallery: ["/embossed-luxury-wedding-bag.jpg"],
  },
  {
    id: "wedding-003",
    title: "Decorative Theme Gift Bag",
    category: "wedding",
    description: "Colorful themed bags for festivals, birthdays, and special occasions.",
    useCase: "Festivals, birthdays, parties",
    image: "/decorative-theme-gift-bag.jpg",
    slug: "decorative-theme-gift-bag",
    specifications: {
      material: "Art Paper",
      sizes: ["Various sizes"],
      gsm: "200-250 GSM",
      moq: "500 pieces",
    },
    features: ["Vibrant colors", "Theme customization", "Decorative elements"],
    gallery: ["/decorative-theme-gift-bag.jpg"],
  },

  // Food Grade Paper Bags
  {
    id: "food-001",
    title: "Bakery Paper Bag",
    category: "food-grade",
    description: "Food-safe paper bags for bread, pastries, and bakery items with grease resistance.",
    useCase: "Bakeries, pastry shops",
    image: "/bakery-paper-bag.jpg",
    slug: "bakery-paper-bag",
    specifications: {
      material: "Food-grade kraft/white paper",
      sizes: ["6x9", "8x10", "10x12"],
      gsm: "60-80 GSM",
      moq: "1000 pieces",
      finishing: ["Grease-resistant coating"],
    },
    features: ["Food-safe certified", "Grease-resistant", "Breathable"],
    gallery: ["/bakery-paper-bag.jpg"],
  },
  {
    id: "food-002",
    title: "Sweet Shop Bag",
    category: "food-grade",
    description: "Hygienic bags for sweets, confectioneries, and dry snacks.",
    useCase: "Sweet shops, confectionery stores",
    image: "/sweet-shop-bag.jpg",
    slug: "sweet-shop-bag",
    specifications: {
      material: "Food-grade paper",
      sizes: ["4x6", "6x9", "8x10"],
      gsm: "60-100 GSM",
      moq: "1000 pieces",
    },
    features: ["Food-safe", "Optional window", "Custom branding"],
    gallery: ["/sweet-shop-bag.jpg"],
  },
  {
    id: "food-003",
    title: "Takeaway Food Bag",
    category: "food-grade",
    description: "Strong and leak-resistant bags for restaurant takeaways and food delivery.",
    useCase: "Restaurants, food delivery, cloud kitchens",
    image: "/takeaway-food-bag.jpg",
    slug: "takeaway-food-bag",
    specifications: {
      material: "Food-grade kraft paper",
      sizes: ["10x12x5", "12x15x6"],
      gsm: "120-150 GSM",
      moq: "500 pieces",
      finishing: ["Leak-resistant coating"],
    },
    features: ["Leak-resistant", "Strong handles", "Eco-friendly"],
  },
  {
    id: "food-004",
    title: "Confectionery Paper Bag",
    category: "food-grade",
    description: "Small bags perfect for candies, chocolates, and small confectionery items.",
    useCase: "Candy stores, chocolate shops",
    image: "/confectionery-bag.jpg",
    slug: "confectionery-paper-bag",
    specifications: {
      material: "Food-grade paper",
      sizes: ["3x5", "4x6"],
      gsm: "60-80 GSM",
      moq: "2000 pieces",
    },
    features: ["Food-safe", "Multiple colors", "Compact size"],
  },

  // Sweet & Designer Boxes
  {
    id: "box-001",
    title: "Premium Sweet Box",
    category: "boxes",
    description: "Elegant boxes for traditional sweets, dry fruits, and festive gifting.",
    useCase: "Sweet shops, festive gifting, dry fruits",
    image: "/premium-sweet-box.jpg",
    slug: "premium-sweet-box",
    specifications: {
      material: "Art Card / Duplex Board",
      sizes: ["6x6x2", "8x8x2", "10x10x3"],
      gsm: "300-400 GSM",
      moq: "500 pieces",
      finishing: ["Window option", "Gold foiling", "Lamination"],
    },
    features: ["Food-safe", "Window panel", "Premium finish"],
  },
  {
    id: "box-002",
    title: "Designer Gift Box",
    category: "boxes",
    description: "Luxury gift boxes with magnetic closure and premium finishing.",
    useCase: "Premium gifting, corporate gifts",
    image: "/designer-gift-box.jpg",
    slug: "designer-gift-box",
    specifications: {
      material: "Rigid board",
      sizes: ["Customizable"],
      gsm: "400+ GSM",
      moq: "300 pieces",
      finishing: ["Magnetic closure", "Foiling", "Embossing"],
    },
    features: ["Magnetic closure", "Rigid structure", "Luxury appeal"],
  },
  {
    id: "box-003",
    title: "Window Box",
    category: "boxes",
    description: "Boxes with transparent window for product visibility, ideal for bakery and gifts.",
    useCase: "Bakery, chocolates, cupcakes",
    image: "/window-box.jpg",
    slug: "window-box",
    specifications: {
      material: "Food-grade card",
      sizes: ["6x6x3", "8x8x4", "10x10x5"],
      gsm: "300 GSM",
      moq: "500 pieces",
    },
    features: ["Clear window", "Food-safe", "Easy assembly"],
  },
  {
    id: "box-004",
    title: "Festive Packaging Box",
    category: "boxes",
    description: "Seasonal and festive boxes for Diwali, Christmas, and special occasions.",
    useCase: "Festival gifting, seasonal products",
    image: "/festive-packaging-box.jpg",
    slug: "festive-packaging-box",
    specifications: {
      material: "Art Card",
      sizes: ["Various sizes"],
      gsm: "300-350 GSM",
      moq: "500 pieces",
    },
    features: ["Festival themes", "Vibrant designs", "Gift-ready"],
  },

  // Corporate & Event Bags
  {
    id: "corp-001",
    title: "Corporate Event Bag",
    category: "corporate",
    description: "Professional bags for corporate events, conferences, and seminars with logo printing.",
    useCase: "Corporate events, conferences, seminars",
    image: "/corporate-event-bag.jpg",
    slug: "corporate-event-bag",
    specifications: {
      material: "Kraft / Art Card",
      sizes: ["10x12x4", "12x15x5"],
      gsm: "200-250 GSM",
      moq: "500 pieces",
      printing: ["Logo printing", "Custom branding"],
    },
    features: ["Professional look", "Durable", "Custom branding"],
  },
  {
    id: "corp-002",
    title: "Conference Welcome Kit Bag",
    category: "corporate",
    description: "Premium bags for welcome kits containing event materials and merchandise.",
    useCase: "Conference kits, welcome packages",
    image: "/conference-welcome-kit-bag.jpg",
    slug: "conference-welcome-kit-bag",
    specifications: {
      material: "Art Card",
      sizes: ["12x15x6", "14x18x6"],
      gsm: "250-300 GSM",
      moq: "300 pieces",
      finishing: ["Matte lamination", "Logo printing"],
    },
    features: ["Large capacity", "Professional design", "Reinforced handles"],
  },
  {
    id: "corp-003",
    title: "Custom Logo Printed Bag",
    category: "corporate",
    description: "Fully customizable bags with your company logo and brand colors.",
    useCase: "Brand promotion, corporate gifting",
    image: "/custom-logo-printed-bag.jpg",
    slug: "custom-logo-printed-bag",
    specifications: {
      material: "Customizable",
      sizes: ["All sizes"],
      gsm: "150-350 GSM",
      moq: "500 pieces",
      printing: ["Full customization"],
    },
    features: ["Full customization", "Brand colors", "Quality printing"],
  },

  // Stationery & Printing
  {
    id: "stat-001",
    title: "Custom Bill Books",
    category: "stationery",
    description: "Professional bill books with company branding for retail and service businesses.",
    useCase: "Retail stores, service providers",
    image: "/custom-bill-books.jpg",
    slug: "custom-bill-books",
    specifications: {
      material: "NCR Paper / Bond Paper",
      sizes: ["A5", "A6", "Custom"],
      moq: "100 books",
      printing: ["Offset printing", "Serial numbering"],
    },
    features: ["Duplicate/Triplicate copies", "Serial numbering", "Custom design"],
  },
  {
    id: "stat-002",
    title: "Corporate Calendars",
    category: "stationery",
    description: "Wall and desk calendars with custom design for corporate gifting.",
    useCase: "Corporate gifting, brand promotion",
    image: "/corporate-calendars.jpg",
    slug: "corporate-calendars",
    specifications: {
      material: "Art Card",
      sizes: ["Wall calendar", "Desk calendar"],
      gsm: "300 GSM",
      moq: "100 pieces",
    },
    features: ["Custom design", "Full color printing", "Quality binding"],
  },
  {
    id: "stat-003",
    title: "Brochures & Catalogs",
    category: "stationery",
    description: "Professional brochures and product catalogs with premium printing.",
    useCase: "Marketing materials, product showcase",
    image: "/brochures-catalogs.jpg",
    slug: "brochures-catalogs",
    specifications: {
      material: "Art Paper / Glossy Paper",
      sizes: ["A4", "A5", "Custom"],
      gsm: "130-170 GSM",
      moq: "500 pieces",
    },
    features: ["Full color printing", "Professional binding", "Various folding options"],
  },
  {
    id: "stat-004",
    title: "Printed Stickers & Labels",
    category: "stationery",
    description: "Custom stickers and labels for product branding and packaging.",
    useCase: "Product labeling, brand stickers",
    image: "/printed-stickers-labels.jpg",
    slug: "printed-stickers-labels",
    specifications: {
      material: "Vinyl / Paper stickers",
      sizes: ["Any size", "Any shape"],
      moq: "1000 pieces",
    },
    features: ["Waterproof option", "Die-cut shapes", "Quality adhesive"],
  },
]
